In [2]:
import pandas as pd
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [4]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [7]:
pd.merge(employees, departments, on="DeptID")#inner join common thhings in both table

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [11]:
pd.merge(employees, departments, on="DeptID",how="left")#ileft join lefty table completely incliuded

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [12]:
pd.merge(employees, departments, on="DeptID",how="right")#right join right table completely incliuded

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [13]:
pd.merge(employees, departments, on="DeptID",how="outer")#outer join both table completely incliuded

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [14]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [17]:
df1

   ID
0   1
1   2

In [19]:
df2

   Score
0     90
1     80

In [20]:
pd.concat([df1,df2])

    ID  Score
0  1.0    NaN
1  2.0    NaN
0  NaN   90.0
1  NaN   80.0

In [16]:
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})

pd.concat([df1, df2], axis=1)

   ID  Score
0   1     90
1   2     80